[id='cloudbal-score-drools-proc']
= Configuring score calculation using Drools

You can use the Drools language to define constraints. Drools score calculation uses incremental calculation, where every score constraint is written as one or more score rules. 

Using the Drools rule engine for score calculation enables you to integrate with other Drools technologies, such as decision tables (XLS or web based), the KIE Workbench, and so on.

.Procedure
To use the Drools rule engine as a score function, simply add a `scoreDrl` resource in the classpath. In the `cloudBalancingSolverConfig.xml` file, add or uncomment the setting:

[source,xml,options="nowrap"]
----
  <scoreDirectorFactory>
    <scoreDrl>org/optaplanner/examples/cloudbalancing/solver/cloudBalancingScoreRules.drl</scoreDrl>
  </scoreDirectorFactory>
----

. We want to make sure that all computers have enough CPU, RAM and network bandwidth to support all their processes, so we make these hard constraints:
+
.cloudBalancingScoreRules.drl - Hard Constraints
====
[source,options="nowrap"]
----
...

import org.optaplanner.examples.cloudbalancing.domain.CloudBalance;
import org.optaplanner.examples.cloudbalancing.domain.CloudComputer;
import org.optaplanner.examples.cloudbalancing.domain.CloudProcess;

global HardSoftScoreHolder scoreHolder;

// ############################################################################
// Hard constraints
// ############################################################################

rule "requiredCpuPowerTotal"
    when
        $computer : CloudComputer($cpuPower : cpuPower)
        accumulate(
            CloudProcess(
                computer == $computer,
                $requiredCpuPower : requiredCpuPower);
            $requiredCpuPowerTotal : sum($requiredCpuPower);
            $requiredCpuPowerTotal > $cpuPower
        )
    then
        scoreHolder.addHardConstraintMatch(kcontext, $cpuPower - $requiredCpuPowerTotal);
end

rule "requiredMemoryTotal"
    ...
end

rule "requiredNetworkBandwidthTotal"
    ...
end
----
====

. If those constraints are met, we want to minimize the maintenance cost, so we add that as a soft constraint:
+
.cloudBalancingScoreRules.drl - Soft Constraints
====
[source,options="nowrap"]
----
// ############################################################################
// Soft constraints
// ############################################################################

rule "computerCost"
    when
        $computer : CloudComputer($cost : cost)
        exists CloudProcess(computer == $computer)
    then
        scoreHolder.addSoftConstraintMatch(kcontext, - $cost);
end
----
====

