[id='cloudbal-class-cloudbalance-ref']
= The `CloudBalance` Class

The `CloudBalance` class has a [path]_@PlanningSolution_
 annotation.

* It holds a list of all computers and processes.
* It represents both the planning problem and (if it is initialized) the planning solution.

. The class holds a collection of processes that Planner can change. We annotate the getter `getProcessList()` with ``@PlanningEntityCollectionProperty``, so that Planner can retrieve the processes that it can change. To save a solution, Planner initializes a new instance of the class with the list of changed processes.

. The `CloudBalance` class also has a `@PlanningScore` annotated property ``score``, which is the `Score` of that solution in its current state.
Planner automatically updates it when it calculates a `Score` for a solution instance; therefore, this property needs a setter.

. Especially for score calculation with Drools, the property `computerList` needs to be annotated with a `@ProblemFactCollectionProperty` so that Planner can retrieve a list of computers (problem facts) and make it available to the Drools engine.

.CloudBalance.java
====
[source,java,options="nowrap"]
----
@PlanningSolution
public class CloudBalance ... {

    private List<CloudComputer> computerList;

    private List<CloudProcess> processList;

    private HardSoftScore score;

    @ValueRangeProvider(id = "computerRange")
    @ProblemFactCollectionProperty
    public List<CloudComputer> getComputerList() {
        return computerList;
    }

    @PlanningEntityCollectionProperty
    public List<CloudProcess> getProcessList() {
        return processList;
    }

    @PlanningScore
    public HardSoftScore getScore() {
        return score;
    }

    public void setScore(HardSoftScore score) {
        this.score = score;
    }

    ...
}
----
====
