[id='optimizer-running-webexamples-proc']
= Running the web examples
Besides the GUI examples, {PRODUCT} also includes a set of web examples for {PLANNER}. The web examples include:

* Vehicle routing: calculating the shortest possible route to pick up all items required for a number of different customers using either http://leafletjs.com/[Leaflet] or http://google.com/maps[Google Maps] visualizations. 
* Cloud balancing: Assigning processes across computers with different specifications and costs. 

.Prerequisites

You have downloaded and unpacked the {PRODUCT} add-ons package, which includes the examples. For instructions about these actions, see <<examples-download-proc>>.

The web examples require several JEE APIs to run, such as:

* Servlet
* JAX-RS
* CDI

These APIs are not required for Planner itself.

.Procedure
. Download a JEE application server, such as JBoss EAP or http://www.wildfly.org/[WildFly] and unzip it.
. In the unpacked `{PRODUCT_FILE}-planner-engine` directory, open the subdirectory `webexamples/binaries` and deploy the `optaplanner-webexamples-*.war` file on the JEE application server. 
+ 
If using JBoss EAP in standalone mode, this can be done by adding the `optaplanner-webexamples-*.war` file to the `JBOSS_home/standalone/deployments` folder. 
. Open the following address in a web browser:  $$http://localhost:8080/optaplanner-webexamples-*/$$ (replace the $$*$$ with the actual version).
