[id='kieserver-central-deploy-proc']
= Deploying {CENTRAL} and {KIE_SERVER}

You can deploy {CENTRAL} on the OpenShift infrastructure together with {KIE_SERVER}. In this case, you can use {CENTRAL} to manage the {KIE_SERVER} and to develop new rules.

.Procedure
. In the OpenShift Web UI, select *Import YAML / JSON* and then select or paste the `rhdm70-full.yaml` file, which is supplied with {PRODUCT}.
. In the *Add Template* window, ensure *Process the template* is selected and click *Continue*.
. Set the following mandatory parameters:
** *Application Name*: the name of the OpenShift application. It is used in the default URLs for {CENTRAL} and {KIE_SERVER}.
** *Decision Central Server Certificate Name*: the name of the certificate in the keystore that you created in <<secrets-central-create-proc>>.
** *Decision Central Server Keystore Password*: the password for the keystore that you created in <<secrets-central-create-proc>>.
** *KIE Server Certificate Name*: the name of the certificate in the keystore that you created in <<secrets-kie-create-proc>>.
** *KIE Server Keystore Password*: the password for the keystore that you created in <<secrets-kie-create-proc>>.
** *ImageStream Namespace*: the name of the OpenShift project.

You can also set other parameters as necessary.
. Click *Create*.
