[id='migrate-kie-projects-proc']
= Migrate KIE projects and applications

COMMENT: Can we migrate projects from before 6.4?

A KIE project is a project created in Decision Central, kmodule.xml...
COMMENT: Need a fuller explanation of what a KIE project is and list of project types.

You must upgrade projects and applications created in Red Hat BRMS 6.4 before you run them in {PRODUCT} {PRODUCT_VERSION}.  When you compile a Red Hat BRMS 6.4 project or application using Decision Manager {PRODUCT_VERSION} artifacts, the compilation will fail. Review the following list of components that have changed in {PRODUCT} {PRODUCT_VERSION} COMMENT: and do what?

[NOTE]
====
This list is list not exhaustive. For a complete list of all changes,COMMENT: should I tell them to run revampi?
====
 
.kie-api
The main API for all projects from the KIE group. The majority of changes occur in the following components:

COMMENT: In some cases I have changed KIE Server to Decision Server in the descriptions. Please confirm that this is correct. What do the * specify in the list. Som items have them, some don't.

* org.kie.api.task.* API
* org.kie.api.executor.* API
* org.kie.api.concurrent.* API
* org.kie.api.builder.* API
* org.kie.api.command.* API
* org.kie.api.runtime.* API

.drools-core
The rules engine at the core of {PRODUCT}.

* org.drools.core.command.*
* org.drools.core.common.*

.kie-server-api
The general API for Decision Server.

* org.kie.server.api.commands.*
* org.kie.server.api.marshalling.*
* org.kie.server.api.model.*
* org.kie.server.api.rest.RestURI constants slightly changed (omitted leading '/')

.kie-server-controller-api
The API for the Decision Server controller. 

* org.kie.server.controller.api.service.*

.kie-server-controller-rest
This module contains the REST API for the Decision Server controller. 

* org.kie.server.controller.rest.RestSpecManagementServiceImpl
* org.kie.server.controller.rest.RestKieServerControllerImpl

.kie-server-client
The Decision Server client.

* org.kie.server.client.SolverServicesClient
* org.kie.server.client.UIServicesClient
* org.kie.server.client.admin.ProcessAdminServicesClient
* org.kie.server.client.ProcessServicesClient
* org.kie.server.client.QueryServicesClient
* org.kie.server.client.JobServicesClient
* org.kie.server.client.UserTaskServicesClient
* org.kie.server.client.KieServicesClient
* org.kie.server.client.KieServicesConfiguration

.kie-server-rest-common
The common Decision Server extension. There were no changes other than the introduction of Swagger annotations which are only for documentation purposes, so everything should be compatible.

.kie-server-rest-drools
The Drools KIE Server extension. There were no changes other than an introduction of Swagger annotations which are only for documentation purposes, so everything should be compatible.

.kie-server-rest-optaplanner
The Optaplanner KIE Server extension. 

* org.kie.server.remote.rest.optaplanner.SolverResource

.optaplanner-benchmark
The benchmarking tool for Business Planner.

* org.optaplanner.benchmark.api.PlannerBenchmarkFactory
* org.optaplanner.benchmark.config.*

.optaplanner-core
The Business Planner engine.

* org.optaplanner.core.api.score.*
* org.optaplanner.core.api.domain.*
* org.optaplanner.core.api.solver.*
* org.optaplanner.core.config.*


