[id='environment-authoring-ha-modify-proc']
= Modifying the template for the High Availability authoring environment

By default, the high-availability authoring template creates a MySQL pod to provide the database server for the {KIE_SERVER}. If you prefer to use PostgreSQL or to use an external server (outside the OpenShift project), you need to modify the template before deploying the environment.

You can also modify the High Availability authoring template to change the number of replicas initially created for {CENTRAL}.

include::modifytemplate-intro.adoc[]

.Procedure

Edit the `rhpam70-authoring-ha.yaml` template file to make any of the following changes as necessary.

* If you want to use PostgreSQL instead of MySQL, replace several blocks of the file, marked with comments from `BEGIN` to `END`, with blocks from the `rhpam70-kieserver-postgresql.yaml` file: 

. Replace the block named `MySQL database parameters` with the block named `PosgreSQL database parameters`. (Take this block and all subsequent replacement blocks from the `rhpam70-kieserver-postgresql.yaml` file.)
. Replace the block named `MySQL service` with the block named `PosgrreSQL service`.
. Replace the block named `MySQL driver settings` with the block named `PosgreSQL driver settings`.
. Replace the block named `MySQL deployment config` with the block named `PosgreSQL deployment config`.
. Replace the block named `MySQL persistent volume claim` with the block named `PosgreSQL persistent volume claim`.

* If you want to use an external database server, make the following changes:
. Remove the following blocks of the file, marked with comments from `BEGIN` to `END`:
+
** `MySQL service`
** `MySQL deployment config`
** `MySQL persistent volume claim`
+
. In the block named `MySQL driver settings`, change the following values:
+
** `RHPAM_DRIVER` to the driver for your database server. The following drivers are available:
+
*** `mysql`
*** `postgresql`
** `RHPAM_SERVICE_HOST` to the host name of your database server,
** `RHPAM_SERVICE_PORT` to the port of your database server,
** `KIE_SERVER_PERSISTENCE_DIALECT` to the dialect for your database server. The following dialects are available:
+
*** `org.hibernate.dialect.MySQLDialect`
*** `org.hibernate.dialect.PostgreSQLDialect`
+
NOTE: The standard {KIE_SERVER} image includes drivers for MySQL (also works for MariaDB) and PostgreSQL external database servers.

* If you want to change the number of replicas initially created for {CENTRAL}, on the line below the comment `## Replicas for Business Central`, change the number of replicas to the desired value.



