[id='environment-immutable-monitoring-proc']
= Deploying monitoring and Smart Router for an environment with immutable servers

If you want to use {CENTRAL} Monitoring and Smart Router for an environment with immutable servers, you must deploy them before deploying any {KIE_SERVERS}. If you do not want to use these components, skip this procedure.

To deploy {CENTRAL} Monitoring and Smart Router for an environment with immutable servers, use the `rhpam70-prod-immutable-monitor.yaml` template file. You can download this file from `{URL_BASE_GITHUB_PAM}/templates`.

.Procedure

. Use one of the following methods to deploy the template:
.. In the OpenShift Web UI, select *Add to Project >  Import YAML / JSON* and then select or paste the `rhpam70-prod-immutable-monitor.yaml` file. In the *Add Template* window, ensure *Process the template* is selected and click *Continue*.
.. To use the OpenShift command line console, prepare the following command line:
+
[subs="verbatim,macros"]
----
oc process -n <project-name> -f <template-path>/rhpam70-prod-immutable-monitor.yaml -v ATTRIBUTE=value -V ATTRIBUTE=value... | oc create -n <project-name> -f -
----
+
In this command line:
+
* Replace `<project-name>` with the name of your project
* Replace `<template-path>` with the path to the downloaded template file.
* Use as many `ATTRIBUTE=value` pairs as needed to set the required attributes. You can view the template file to see descriptions for the attributes.
+
. Set the following mandatory attributes:
** *Application Name* (`APPLICATION_NAME`): the name of the OpenShift application. It is used in the default URLs for {CENTRAL} and Smart Router.
** *Maven repository URL* (`MAVEN_REPO_URL`): a URL for a Maven repository. You must upload all the processes (KJAR files) that are to be deployed in your environment into this repository.
** *Maven repository username* (`MAVEN_REPO_USERNAME`): the username for the Maven repository. 
** *Maven repository password* (`MAVEN_REPO_PASSWORD`): the username for the Maven repository. 
** *Business Central Server Certificate Name* (`BUSINESS_CENTRAL_HTTPS_NAME`): the name of the certificate in the keystore that you created in <<secrets-central-create-proc>>.
** *Business Central Server Keystore Password* (`BUSINESS_CENTRAL_HTTPS_PASSWORD`): the password for the keystore that you created in <<secrets-central-create-proc>>.
** *ImageStream Namespace* (`IMAGE_STREAM_NAMESPACE`): the namespace where the image streams are available. If the image streams were already available in your OpenShift environment (see <<imagestreams-file-install-proc>>), the namespace is `openshift`. If you have installed the image streams file, the namespace is the name of the OpenShift project.
+
You can also set other parameters as necessary.
. Complete the creation of the environment. Depending on the metod that you are using:
.. In the OpenShift Web UI, click *Create*.
.. Complete and run the command line.
