[id='environment-immutable-modify-proc']
= Modifying the server template for an immutable server environment

By default, the immutable server template creates a separate PostgreSQL pod to provide the database server for each replicable {KIE_SERVER}. If you prefer to use MySQL or to use an external server (outside the OpenShift project), you need to modify the `rhpam70-prod-immutable-kieserver.yaml` template before deploying the server.

include::modifytemplate-intro.adoc[]

.Procedure

* If you want to use MySQL instead of PostgreSQL, replace several blocks of the file, marked with comments from `BEGIN` to `END`, with blocks from the `rhpam70-kieserver-mysql.yaml` file: 

. Replace the block named `PostgreSQL database parameters` with the block named `MySQL database parameters`. (Take this block and all subsequent replacement blocks from the `rhpam70-kieserver-postgresql.yaml` file.)
. Replace the block named `PostgreSQL service` with the block named `MySQL service`.
. Replace the block named `PostgreSQL driver settings` with the block named `MySQL driver settings`.
. Replace the block named `PostgreSQL deployment config` with the block named `MySQL deployment config`.
. Replace the block named `PostgreSQL persistent volume claim` with the block named `MySQL persistent volume claim`.

* If you want to use an external database server, make the following changes:
. Remove the following blocks of the file, marked with comments from `BEGIN` to `END`:
+
** `PostgreSQL service`
** `PostgreSQL deployment config`
** `PostgreSQL persistent volume claim`
+
. In the block named `PostgreSQL driver settings`, change the following values:
+
** `RHPAM_DRIVER` to the driver for your database server. The following drivers are available:
+
*** `mysql`
*** `postgresql`
** `RHPAM_SERVICE_HOST` to the host name of your database server,
** `RHPAM_SERVICE_PORT` to the port of your database server,
** `KIE_SERVER_PERSISTENCE_DIALECT` to the dialect for your database server. The following dialects are available:
+
*** `org.hibernate.dialect.MySQLDialect`
*** `org.hibernate.dialect.PostgreSQLDialect`
+
NOTE: The standard {KIE_SERVER} image includes drivers for MySQL (also works for MariaDB) and PostgreSQL external database servers.
