[id='environment-authoring-single-modify-proc']
= Modifying the template for the single authoring environment

By default, the single authoring template uses the H2 database with permanent storage. If you prefer to create a MySQL or PostgreSQL pod or to use an external database server (outside the OpenShift project), you need to modify the template before deploying the environment.

include::modifytemplate-intro.adoc[]

.Procedure
Edit the `rhpam70-authoring-ha.yaml` template file to make any of the following changes as necessary.

* If you want to use MySQL instead of the H2 database, you need to replace several blocks of the file, marked with comments from `BEGIN` to `END`, with blocks from the `rhpam70-kieserver-mysql.yaml` file that are also marked with comments. You also need to remove several other blocks and to add blocks in designated locations:

. Replace the block named `H2 database parameters` with the block named `MySQL database parameters`. (Take this block and all subsequent replacement blocks from the `rhpam70-kieserver-mysql.yaml` file.)
. Replace the block named `H2 driver settings` with the block named `MySQL driver settings`
. Replace the block named `H2 persistent volume claim` with the block named `MySQL persistent volume claim`.
. Remove the blocks named `H2 volume mount` and `H2 volume settings`
. Under the comment `Place to add database service`, add the block named `MySQL service`
. Under the comment `Place to add database deployment config`, add the block named `MySQL deployment config`

* If you want to use PostgreSQL instead of the H2 database, you need to replace several blocks of the file, marked with comments from `BEGIN` to `END`, with blocks from the `rhpam70-kieserver-postgresql.yaml` file that are also marked with comments. You also need to remove several other blocks and to add blocks in designated locations:

. Replace the block named `H2 database parameters` with the block named `PostgreSQL database parameters`. (Take this block and all subsequent replacement blocks from the `rhpam70-kieserver-postgresql.yaml` file.)
. Replace the block named `H2 driver settings` with the block named `PostgreSQL driver settings`
. Replace the block named `H2 persistent volume claim` with the block named `PostgreSQL persistent volume claim`.
. Remove the blocks named `H2 volume mount` and `H2 volume settings`
. Under the comment `Place to add database service`, add the block named `PostgreSQL service`
. Under the comment `Place to add database deployment config`, add the block named `PostgreSQL deployment config`

* If you want to use an external database server, make the following changes:
. Remove the following blocks of the file, marked with comments from `BEGIN` to `END`:
+
** `H2 volume mount`
** `H2 volume settings`
** `H2 persistent volume claim`
+
. In the block named `H2 driver settings`, change or add the following values:
+
** `RHPAM_DRIVER` to the driver for your database server. The following drivers are available:
+
*** `mysql`
*** `postgresql`
** `RHPAM_SERVICE_HOST` to the host name of your database server,
** `RHPAM_SERVICE_PORT` to the port of your database server,
** `KIE_SERVER_PERSISTENCE_DIALECT` to the dialect for your database server. The following dialects are available:
+
*** `org.hibernate.dialect.MySQLDialect`
*** `org.hibernate.dialect.PostgreSQLDialect`
+
NOTE: The standard {KIE_SERVER} image includes drivers for MySQL (also works for MariaDB) and PostgreSQL external database servers.

** Remove the `name` and `value` lines for the `RHPAM_XA_CONNECTION_PROPERTY_URL` setting. 
