[id='environment-managed-deploy-proc']
= Deploying a managed environment

After modifying the template for a managed environment as necessary, you must deploy the environment using the template.

.Procedure

. Use one of the following methods to deploy the template:
.. In the OpenShift Web UI, select *Add to Project >  Import YAML / JSON* and then select or paste the template file. In the *Add Template* window, ensure *Process the template* is selected and click *Continue*.
.. To use the OpenShift command line console, prepare the following command line:
+
[subs="verbatim,macros"]
----
oc new-app -f <template-file-name> -p PARAMETER=value -p PARAMETER=value...
----
+
In this command line:
+
* Replace `<project-name>` with the name of your project
* Replace `<template-file name>` with the full pathname of the template file that you have modified.
* Use as many `ATTRIBUTE=value` pairs as needed to set the required attributes. You can view the template file to see descriptions for the attributes.
+
. Set the following mandatory attributes:
** *Application Name* (`APPLICATION_NAME`): the name of the OpenShift application. It is used in the default URLs for {CENTRAL} and {KIE_SERVER}. OpenShift also uses the application name to create a separate set of deployment configurations, services, routes, labels, and artifacts. You can deploy several applications using the same template into the same project, as long as you use different application names. 
** *Maven repository URL* (`MAVEN_REPO_URL`): a URL for a Maven repository. You must upload all the processes (KJAR files) that are to be deployed in your environment into this repository.
** *Maven repository username* (`MAVEN_REPO_USERNAME`): the username for the Maven repository. 
** *Maven repository password* (`MAVEN_REPO_PASSWORD`): the username for the Maven repository. 
** *Business Central Server Certificate Name* (`BUSINESS_CENTRAL_HTTPS_NAME`): the name of the certificate in the keystore that you created in <<secrets-central-create-proc>>.
** *Business Central Server Keystore Password* (`BUSINESS_CENTRAL_HTTPS_PASSWORD`): the password for the keystore that you created in <<secrets-central-create-proc>>.
** *KIE Server Certificate Name* (`KIE_SERVER_HTTPS_NAME`): the name of the certificate in the keystore that you created in <<secrets-kie-create-proc>>.
** *KIE Server Keystore Password* (`KIE_SERVER_HTTPS_PASSWORD`): the password for the keystore that you created in <<secrets-kie-create-proc>>.
** *ImageStream Namespace* (`IMAGE_STREAM_NAMESPACE`): the namespace where the image streams are available. If the image streams were already available in your OpenShift environment (see <<imagestreams-file-install-proc>>), the namespace is `openshift`. If you have installed the image streams file, the namespace is the name of the OpenShift project.
+
You can also set other parameters as necessary. Notably, you can set the following user names and passwords:
** *KIE Admin User* (`KIE_ADMIN_USER`) and *KIE Admin Password* (`KIE_ADMIN_PWD`): the user name and password for the administrative user in {CENTRAL} Monitoring.
** *KIE Server User* (`KIE_SERVER_USER`) and *KIE Server Password* (`KIE_SERVER_PWD`): the user name and password that a client application must use to connect to any of the {KIE_SERVERS}.
 . Complete the creation of the environment. Depending on the method that you are using:
.. In the OpenShift Web UI, click *Create*.
.. Complete and run the command line.
