[id='kieserver-configure-central-proc']
= Configuring a {KIE_SERVER} to connect to {CENTRAL}

You can configure a {KIE_SERVER} to connect to an existing {CENTRAL}. You can also configure the name of the server template. The server becomes a part of that server template; any decision services deployed on the template are deployed on this server.

IMPORTANT: if you are deploying the {KIE_SERVER} on OpenShift, see ??? for instructions about configuring it to connect to a {CENTRAL}

.Procedure

. Install the {KIE_SERVER}. See ??? for instructions.
. In the ??? file, set the following properties:
** *org.kie.server.controller.user*: user name of an account that can log on to the {CENTRAL}.
** *org.kie.server.controller.pwd*: password for the account.
** *org.kie.server.controller*: the URL for the user interface of the {CENTRAL}.
** *org.kie.server.id*: the name of a server template. If this server template does not exist on the {CENTRAL}, it is created automatically when the {KIE_SERVER} connects to the {CENTRAL}.
. Start or restart the {KIE_SERVER}.