[id='kieserver-configure-runservice-proc']
= Configuring a {KIE_SERVER} to run a decision service

You can configure a {KIE_SERVER} to load and run a decision service automatically without using a {CENTRAL}. The service must be present in a Maven repository. You need access information for the repository and the GAV values for the service.

IMPORTANT: do not use this procedure for a {KIE_SERVER} deployed on OpenShift. See ??? fr instructions ablut configuring a a {KIE_SERVER} to load and run a decision service from a Maven repository.


.Procedure

. Install the {KIE_SERVER}. See ??? for instructions.
. In the ??? file, set the following properties:
** *???*: URL for the Maven repository.
** *???*: user name for the Maven repository.
** *???*: password for the Maven repository.
. Start or restart the {KIE_SERVER}.
. To load a service into a container in the {KIE_SERVER}, run the following command to send an API request:
[subs="verbatim,macros"]
----
$ curl -H "Content-Type: application/json" -X PUT -d '{"container-id" : "<containerID>","release-id" : {"group-id" : "<groupID>","artifact-id" : "<artifactID>","version" : "<version>"}}' http://<serverhost>:<serverport>/kie-server/services/rest/server/containers/<containerID>
----

where:
** *<containerID>* is the identifier for the container. You can use any random identifier but it must be the same in both places in the command (the URL and the data).
** *<groupID>*, *<artifactID>*, *version* are GAV values.
** *<serverhost>* is the host name for the KIE server, or `localhost` if you are running the command on the same host as the KIE server.
** *<serverport>* is the port number for the KIE server
For example:
[subs="verbatim,macros"]
----
curl -H "Content-Type: application/json" -X PUT -d '{"container-id" : "kie1","release-id" : {"group-id" : "org.kie.server.testing","artifact-id" : "container-crud-tests1","version" : "2.1.0.GA"}}' http://localhost:39043/kie-server/services/rest/server/containers/kie1
----

??? might need another command to start the container