[id='customimage-rpm-proc']
:componentimage: kieserver
:component: {KIE_SERVER}
= Creating a custom {KIE_SERVER} image with an additional RPM package

You can create a custom {KIE_SERVER} image where an additional RPM package is installed. You can push this image into your custom registry and then use it to deploy the {KIE_SERVER}.

.Procedure

include::customimage-download-step.adoc[]
. Acquire the RPM package. This package must install on a Red Hat Enterprise Linux 8 system. For this example we use the `busybox` package from Fedora 30, which installs on Red Hat Enterprise Linux 8:
+
[subs="attributes,verbatim,macros,quotes"]
----
wget \https://download-cc-rdu01.fedoraproject.org/pub/fedora/linux/releases/30/Everything/x86_64/os/Packages/b/busybox-1.28.3-3.fc30.x86_64.rpm
----
+
. Create a `Dockerfile` that defines a custom image based on the base image. The file must copy the RPM file and install it. The `root` user is required to install an RPM file; after the installation the system must revert to `USER 185`, the {EAP} user. The following example shows the content of the `Dockerfile` file:
+
[subs="attributes,verbatim,macros,quotes"]
----
FROM registry.redhat.io/{PRODUCT_INIT}-7/{PRODUCT_INIT}-kieserver-rhel8:7.7.0
COPY busybox-1.28.3-3.fc30.x86_64.rpm /tmp/
USER root
RUN rpm -ivh /tmp/busybox-1.28.3-3.fc30.x86_64.rpm
RUN rm -f /tmp/busybox-1.28.3-3.fc30.x86_64.rpm
USER 185
----
+
Replace the name of the RPM file as necessary. You might need to install several RPM files, in this case, use several `COPY` and `RUN` commands.
+
include::customimage-build-step.adoc[]
include::customimage-verify-partstep.adoc[]
In the shell prompt for the image, enter the command to test that the RPM is installed, then enter `exit`. For example, for `busybox`:
+
[subs="attributes,verbatim,macros,quotes"]
----
[jboss@c2fab36b778e ~]$ which busybox
/usr/sbin/busybox
[jboss@c2fab36b778e ~]$ exit
----
+
include::customimage-push-step.adoc[]

.Next steps

include::customimage-nextsteps.adoc[]

For instructions about deploying the {KIE_SERVER} using the operator, see <<operator-deploy-kieserver-proc>>.
