[id='environment-authoring-managed-con']
= Authoring or managed server environment
You can deploy an environment for creating and modifying {ASSETS} using {CENTRAL} and for running them in {KIE_SERVERS} managed by {CENTRAL}. This environment consists of {CENTRAL} and one or more {KIE_SERVERS}.

You can use {CENTRAL} both to develop {ASSETS} and to deploy them to one or several {KIE_SERVERS}. For example, you can deploy test versions of {ASSETS} to one {KIE_SERVER} and production versions to another {KIE_SERVER}. 

To avoid accidentally deploying wrong versions to a production {KIE_SERVER}, you can create separate environments to author {ASSETS} (_authoring environment_) and to manage deployment of production {ASSETS} (_managed server environment_). You can use a shared external Maven repository between these environments, so that {ASSETS} developed in the authoring environment are available in the managed server environment. However, the procedures to deploy these environments are the same.

Depending on your needs, you can deploy either a single authoring or managed server environment or a high-availability (HA) authoring or managed server environment. In a single environment, the {CENTRAL} pod is not replicated; only a single copy of {CENTRAL} is used. In an HA environment, you can scale {CENTRAL}. 

An HA environment provides maximum reliability and responsiveness for authoring {ASSETS} in {CENTRAL}, but has higher memory and storage requirements, and also requires support for persistent volumes with ReadWriteMany mode (not available on OpenShift Online and OpenShift Dedicated).

IMPORTANT: In the current version, the high-availability functionality is a technology preview.

You can scale {KIE_SERVER} pods as necessary in any version of the authoring or managed server environment.

To deploy an authoring or managed server environment, first deploy the single or high-availability full environment template. This deployment includes {CENTRAL} and a single {KIE_SERVER}.

To add additional {KIE_SERVERS}, you can deploy the {KIE_SERVER} template in the same project.
