[id='environment-authoring-ha-proc']
// definitions for RH-SSO include
:kieandcentral:
:LOCAL_CENTRAL: {CENTRAL}
ifdef::PAM[]
= Deploying a high-availability authoring environment

To deploy a high-availability authoring environment, use the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-authoring-ha.yaml` template file. 
endif::PAM[]
ifdef::DM[]
= Deploying a high-availability full environment template

To deploy a high-availability full environment template, use the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-full-ha.yaml` template file. 
endif::DM[]
You can download the file from the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page for {PRODUCT} {PRODUCT_VERSION}.
ifdef::PAM[]

If you want to modify the environment defined by the template file, see <<environment-authoring-ha-modify-proc>>.
endif::PAM[]

IMPORTANT: In the current version, the high-availability functionality is a technology preview.

.Procedure
. Use one of the following methods to deploy the template:
* In the OpenShift Web UI, select *Add to Project -> Import YAML / JSON* and then select or paste the 
ifdef::PAM[`{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-authoring-ha.yaml`]
ifdef::DM[`{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-full-ha.yaml`]
file. In the *Add Template* window, ensure *Process the template* is selected and click *Continue*.
* To use the OpenShift command line console, prepare the following command line:
+
ifdef::PAM[]
[subs="verbatim,macros"]
----
oc new-app -f <template-path>/{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-authoring-ha.yaml -p BUSINESS_CENTRAL_HTTPS_SECRET=businesscentral-app-secret -p KIE_SERVER_HTTPS_SECRET=kieserver-app-secret 
----
endif::PAM[]
ifdef::DM[]
[subs="verbatim,macros"]
----
oc new-app -f <template-path>/{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-full-ha.yaml [-p <parameter>=<value> ...] 
----
endif::DM[]
+
In this command line:
+
** Replace `<template-path>` with the path to the downloaded template file.
** Use as many `-p PARAMETER=value` pairs as needed to set the required parameters. You can view the template file to see descriptions for all parameters.
+
. Set the following parameters as necessary:
+
include::authoring-params.adoc[]
. Complete the creation of the environment, depending on the method that you are using:
* In the OpenShift Web UI, click *Create*.
* Complete and run the command line.
