[id='freeform-con']
= Freeform server environment
You can deploy a freeform server environment that includes several different pods running {KIE_SERVER}. These servers can run different services for staging or productiuon purposes. You can add and remove server instances as necessary at any time. 

The environment includes a pod with {CENTRAL} Monitoring; use it to monitor and, when necessary, manage the execution of servics on {KIE_SERVERS}. 

This environment does not include Smart Router.

You can deploy two types of {KIE_SERVER} instances (sets of replicated pods): managed and immutable. Each {KIE_SERVER} instance can be separately scaled as necessary.

On a _managed_ {KIE_SERVER} instance, by default, no services are initially loaded. You can also configure the deployment to load a service. You must use {CENTRAL} Monitoring to deploy, load, and unload processes on the server. 

You must provide a Maven repository with the processes (KJAR files) that you want to deploy on the servers. Your integration process must ensure that the required versions of the processes are uploaded to the Maven repository. You can use {CENTRAL} in a development environment to create the processes and upload them to the Maven repository.

On an _immutable_ {KIE_SERVER} instance, any services must be loaded onto at the time the image is created. You cannot load or unload services on a running immutable {KIE_SERVER}. The advantage of this approach is that the {KIE_SERVER} with the services in it runs like any other containerized service and does not require specialized management. The {KIE_SERVER} runs like any other pod on the OpenShift environment; you can use any container-based integration workflows as necessary. 

Immutable {KIE_SERVER} instances build services from source during deployment. You must make the source available in a Git repository.

You can use {CENTRAL} Monitoring to view monitoring information for all {KIE_SERVER} instances in the environment, including immutable servers.

{KIE_SERVER} instances use database servers. Usually the database servers also run in pods, though you can set up a {KIE_SERVER} instance to use an external database server. 
