[id='hacep-server-proc']
= Implementing the HA CEP server

The high-availability (HA) CEP server runs on the {OPENSHIFT} environment. It includes all necessary {PRODUCT_DROOLS} rules and other code required to process events.

You must prepare the source, build it, and then deploy it on {OPENSHIFT}. 

.Procedure

.  Download the `{PRODUCT_FILE}-reference-implementation.zip` product deliverable file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page of the Red Hat Customer Portal.
. Extract the contents of the file and then uncompress the `{PRODUCT_FILE}-openshift-drools-hacep-distribution.zip` file.
. Change to the `openshift-drools-hacep-distribution/sources` directory.
. Review and modify the server code based on the sample project in the `sample-hacep-project/sample-hacep-project-kjar` directory. The complex event processing logic is defined by the DRL rules in the `src/main/resources/org.drools.cep` subdirectory.
. Build the project using the standard Maven command:
+
----
mvn clean install -DskipTests
----
+
. Use the OpenShift operator infrastructure to install Red Hat AMQ Streams. For information about installing Red Hat AMQ Streams, see https://access.redhat.com/documentation/en-us/red_hat_amq/7.3/html/using_amq_streams_on_openshift_container_platform/index[_Using AMQ Streams on OpenShift Container Platform_].
. Using the `KafkaTopic` resource on {OPENSHIFT}, create the topics from all the YAML files in the `kafka-topics` subdirectory. 
+
For instructions about creating topics using the `KafkaTopic` resource, see https://access.redhat.com/documentation/en-us/red_hat_amq/7.4/html/using_amq_streams_on_openshift_container_platform/using-the-topic-operator-str[Using the topic operator] in the Red Hat AMQ documentation.
+
. In order to enable application access to the ConfigMap that is used in the leader election, you must configure role-based access control. Change to the `springboot` directory and enter the following commands:
+
----
oc create -f kubernetes/service-account.yaml
oc create -f kubernetes/role.yaml
oc create -f kubernetes/role-binding.yaml
----
+
For more information about configuring role-based access control in {OPENSHIFT}, see https://access.redhat.com/documentation/en-us/openshift_container_platform/4.1/html/authentication/using-rbac[Using RBAC to define and apply permissions] in the {OPENSHIFT} product documentation.
+
. In the `springboot` directory, enter the following commands to create the image for deployment and push it into the repository configured for your OpenShift environment:
+
----
oc new-build --binary --strategy=docker --name openshift-kie-springboot
oc start-build openshift-kie-springboot --from-dir=. --follow----
----
+
. Enter the following command to detect the name of the image that was built:
+
----
oc get is/openshift-kie-springboot -o template --template='{{range .status.tags}}{{range .items}}{{.dockerImageReference}}{{end}}{{end}}'
----
+
. Edit the `kubernetes/deployment.yaml` file. Replace the existing image URL with the result of the previous command, removing all characters at the end starting with the `@` symbol, then add `:latest` to the line. For example: 
+
----
image: image-registry.openshift-image-registry.svc:5000/hacep/openshift-kie-springboot:latest
----
+
. Enter the following command to deploy the image:
+
----
oc apply -f kubernetes/deployment.yaml
----
