[id='hacep-server-os4-proc']
= Building and deploying the HA CEP server image on {OPENSHIFT} 4.1

If you have an {OPENSHIFT} 4.1 environment, complete the following procedure to build and deploy the HA CEP server image.

.Prerequisites

. You prepared the source for the HA CEP server image, as described in <<hacep-server-prepare-proc>>.

.Procedure
. Use the OpenShift operator infrastructure to install Red Hat AMQ Streams or Strimzi. For information about installing Red Hat AMQ Streams, see https://access.redhat.com/documentation/en-us/red_hat_amq/7.3/html/using_amq_streams_on_openshift_container_platform/index[Using AMQ Streams on OpenShift Container Platform].
. Using the Kafka Topic user interface or the Kafka command line, create the topics from all the YAML files in the `kafka-topics` subdirectory. 
+
For instructions about creating topics in Kafka, see https://kafka.apache.org/documentation/#topicconfigs[Topic-level configs] in the Apache Kafka documentation.
+
. Enter the following commands to build the docker image and push into docker hub:  
+
----
docker login --username=<user username>
docker build -t <user_username>/openshift-kie-springboot:<tag> .  
docker push <user_username>/openshift-kie-springboot:<tag>
----
+
. In the OpenShift user interface, create a YAML source. Paste in the contents of the `kubernetes/deployment_registry.yaml`. Change the docker image name as necessary. Then click *Deploy* to deploy the server.
