[id='hacep-server-proc']
= Implementing the HA CEP server

The high-availability CEP server runs on the {OPENSHIFT} environment. It includes all necessary Drools rules and other code required to process events.

You must prepare the source, then build it, and then deploy it in {OPENSHIFT}. 

.Procedure

. Download the ??? product deliverable file from the {PRODUCT_DOWNLOAD_LINK}[Software Downloads] page of the Red Hat Customer Portal.
. Extract the contents of the file.
. Develop the server code based on the project in the `sample-hacep-project/sample-hacep-project-kjar` directory. In partiular, place the Drools language source files in the `src/main/recources/org.drools.cep` subdirectory.
. Build the project using the standard Maven command:
+
----
mvn clean install
----
+
??? I STILL DO NOT SEE HOW THIS KJAR IS PICKED UP IN THE SUBSEQUENT DOCKER BUILD ???
+
. Use the OpenShift operator infrastructure to install Red Hat AMQ Streams or Strimzi. For information about installing Red Hat AMQ Streams, see https://access.redhat.com/documentation/en-us/red_hat_amq/7.3/html/using_amq_streams_on_openshift_container_platform/index[Using AMQ Streams on OpenShift Container Platform].
. Using the `KafkaTopic` resource on {OPENSHIFT}, create the topics from all the YAML files in the `kafka-topics` subdirectory. 
+
For instructions about creating topics using the `KafkaTopic` resource, see https://access.redhat.com/documentation/en-us/red_hat_amq/7.4/html/using_amq_streams_on_openshift_container_platform/using-the-topic-operator-str[Using the topic operator] in the Red Hat AMQ documentation.
+
. Enter the following commands to build the docker image and push into docker hub:  
+
----
docker login --username=<user username>
docker build -t <user_username>/openshift-kie-springboot:<tag> .  
docker push <user_username>/openshift-kie-springboot:<tag>
----
+
. In the OpenShift user interface, create a YAML source. Paste in the contents of the `kubernetes/deployment_registry.yaml`. Change the docker image name as necessary. Then click *Deploy* to deploy the server.
