[id='kieserver-additional-deploy-proc']
= Deploying an additional {KIE_SERVER}

As a part of a managed server infrastructure, you can deploy an additional {KIE_SERVER} on the OpenShift infrastructure. You can then use {CENTRAL} to deploy, undeploy, and manage {ASSETS} on this {KIE_SERVER}.

To deploy an additional {KIE_SERVER}, use the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver.yaml` template file. You can download the file from the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html[Software Downloads] page for {PRODUCT} {PRODUCT_VERSION}.


.Procedure

. Use one of the following methods to deploy the template:
* In the OpenShift Web UI, select *Add to Project -> Import YAML / JSON* and then select or paste the `{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver.yaml` file. In the *Add Template* window, ensure *Process the template* is selected and click *Continue*.
* To use the OpenShift command line console, prepare the following command line:
+
[subs="attributes,verbatim,macros"]
----
oc new-app -f <template-path>/{PRODUCT_INIT}{ENTERPRISE_VERSION_SHORT}-kieserver.yaml -p <parameter>=<value> ...  
----
+
In this command line:
+
** Replace `<template-path>` with the path to the downloaded template file.
** Use as many `-p PARAMETER=value` pairs as needed to set the required parameters. You can view the template file to see descriptions for all parameters.
+
. Set the following parameters:
+
** *KIE server controller service*: The OpenShift service name for the {CENTRAL} that you installed for this environment.
** *KIE server controller user*: The controller user name for logging onto the {CENTRAL} that you configured.
** *KIE server controller password*: The controller password for logging onto the {CENTRAL} that you configured.
** *KIE Server ID*: The name of the server template on the {CENTRAL} that this server is to join.
** *Maven repository URL* (`MAVEN_REPO_URL`): The URL for the Maven repository with {ASSETS}. If you configured an external Maven repository for the {CENTRAL}, use the URL for it. Otherwise, use the URL for the Maven repository built into the {CENTRAL}: `<{URL_COMPONENT_CENTRAL_UNDER}_URL>/maven2/`.
** *Maven repository username* (`MAVEN_REPO_USERNAME`): The user name for the Maven repository. If you configured an external Maven repository for the {CENTRAL}, use the user name for it. Otherwise, use the controller user name.  
** *Maven repository password* (`MAVEN_REPO_PASSWORD`): The password for the Maven repository. Otherwise, use the controller password.
+
. Complete the creation of the environment, depending on the method that you are using:
* In the OpenShift Web UI, click *Create*.
* Complete and run the command line.
