[id='operator-modify-proc']
= Modifying an environment that is deployed using operators

If an environment is deployed using operators, you can not modify it using typical OpenShift methods. For example, if you delete a pod, it is re-created automatically with the same parameters.

??? so how do we do S2I lifecycle where we expect to create a new pod from new source and then displace the old none?

To modify the environment, you mist modify the YAML description of the environment.

.Procedure
. Enter your project in the OpenShift Web console. 
. In the OpenShift Web console navigation panel, select *Operators* and then *Subscriptions*.
. Click the name of the subscription that containt `businessautomation`. Information about this subscription is displayed.
. Under the *Installed version* heading, click the version name of the subscription. An overview of the subscription is displayed.
. Select the *Instances* tab.
. Click the name of a deployed environment. 
. Select the *YAML* tab. A YAML source is displayed.
. You can make the following modifications to the source:

??? I have no idea what can be meaningfully changed and how. I guess one can add and delete lines under deployments but no idea what one can meaningfully add or where to set the parameters for anything one adds - for example, the settings for an immutable S2I build.
 