[id='secret-adminuser-create-proc']
:INCLUDECENTRAL!:
ifeval::["{context}"=="openshift-authoring"]
:INCLUDECENTRAL: {CENTRAL}
endif::[]
ifeval::["{context}"=="openshift-authoring-managed"]
:INCLUDECENTRAL: {CENTRAL}
endif::[]
ifeval::["{context}"=="openshift-freeform"]
:INCLUDECENTRAL: {CENTRAL} Monitoring
endif::[]
ifeval::["{context}"=="openshift-managed"]
:INCLUDECENTRAL: {CENTRAL} Monitoring
endif::[]
//immutable handled separately, so do not define INCLUDECENTRAL for it


= Creating the secret for the administrative user

You must create a secret that contains the user name and password for a {PRODUCT} administrative user account. This secret is required for deploying {PRODUCT} using any template except the trial template. 

If you are using multiple templates to deploy components of {PRODUCT}, use the same secret for all these deployments. The components utilize this user account to communicate with each other.

ifdef::INCLUDECENTRAL[]
You can also use this user account to log in to {INCLUDECENTRAL}. If you do not use RH-SSO or LDAP authentication, use this account to create other user accounts.
endif::INCLUDECENTRAL[]
ifdef::PAM[]
ifeval::["{context}"=="openshift-immutable"]
If you deploy the immutable monitoring template, you can also use this user account to log in to {CENTRAL} Monitoring. If you do not use RH-SSO or LDAP authentication, use this account to create other user accounts.
endif::[]
endif::PAM[]

[IMPORTANT]
====
If you use RH-SSO or LDAP authentication, the same user with the same password must be configured in your authentication system with the `kie-server,rest-all,admin` roles for {PRODUCT}.
====

.Procedure

// the name is rhpam-credentials even for RHDM - this is the example value used in templates
Use the `oc` command to generate a secret named `kie-admin-user-secret` from the user name and password:
+
[subs="attributes,verbatim,macros"]
----
$ oc create secret generic rhpam-credentials -from-literal=KIE_ADMIN_USER=adminUser --from-literal=KIE_ADMIN_PWD=adminPassword
----
+
In this command, replace _adminPassword_ with the password for the administrative user. Optionally, you can replace _adminUser_ with another user name for the administrative user.
