[id='template-deploy-mandatory-{subcontext}-proc']
= Setting required parameters

// local variables depending on the assembly context
:params_central!:
:params_kieserver!:
:params_kieserver_s2i!:
:params_kieserver_container_deployment!:
:params_startup_strategy_first!:
:params_multideploy!:
:params_mandatory_maven!:


ifeval::["{subcontext}"=="freeform-monitor"]
:params_central:
:params_kieserver:
:params_mandatory_maven:
endif::[]

ifeval::["{subcontext}"=="freeform-server-managed"]
:params_kieserver:
:params_kieserver_container_deployment:
:params_startup_strategy_first:
:params_multideploy:
:params_mandatory_maven:
endif::[]

ifeval::["{subcontext}"=="freeform-server-immutable"]
:params_kieserver:
:params_kieserver_s2i:
:params_startup_strategy_first:
:params_multideploy:
endif::[]


The following parameters of the template are required in all cases. 

.Procedure

. Set the following parameters:
ifdef::params_startup_strategy_first[]
** *KIE Server Startup Strategy* (`KIE_SERVER_STARTUP_STRATEGY`). This parameter must be set to `OpenShiftStartupStrategy` to ensure that {LOCAL_CENTRAL} connects to all {KIE_SERVER} instances automatically, using an OpenShift API.
endif::params_startup_strategy_first[]
ifdef::params_central[]
** *{LOCAL_CENTRAL} Server Keystore Secret Name* (`{CENTRAL_CAPITAL_UNDER}_HTTPS_SECRET`): The name of the secret for {CENTRAL}, as created in <<secrets-central-create-proc>>.
endif::params_central[]
ifdef::params_kieserver[]
** *KIE Server Keystore Secret Name* (`KIE_SERVER_HTTPS_SECRET`): The name of the secret for {KIE_SERVER}, as created in <<secrets-kie-create-proc>>.
endif::params_kieserver[]
ifdef::params_central[]
** *{LOCAL_CENTRAL} Server Certificate Name* (`{CENTRAL_CAPITAL_UNDER}_HTTPS_NAME`): The name of the certificate in the keystore that you created in <<secrets-central-create-proc>>. 
** *{LOCAL_CENTRAL} Server Keystore Password* (`{CENTRAL_CAPITAL_UNDER}_HTTPS_PASSWORD`): The password for the keystore that you created in <<secrets-central-create-proc>>.
endif::params_central[]
ifdef::params_kieserver[]
** *KIE Server Certificate Name* (`KIE_SERVER_HTTPS_NAME`): The name of the certificate in the keystore that you created in <<secrets-kie-create-proc>>.
** *KIE Server Keystore Password* (`KIE_SERVER_HTTPS_PASSWORD`): The password for the keystore that you created in <<secrets-kie-create-proc>>.
endif::params_kieserver[]
** *Application Name* (`APPLICATION_NAME`): The name of the OpenShift application. It is used in the default URLs for {CENTRAL} Monitoring and {KIE_SERVER}. OpenShift uses the application name to create a separate set of deployment configurations, services, routes, labels, and artifacts. 
ifdef::params_multideploy[]
You can deploy several applications using the same template into the same project, as long as you use different application names. Also, the application name determines the name of the server configuration (server template) on the {LOCALCENTRAL} that the {KIE_SERVER} is to join. If you are deploying several {KIE_SERVERS}, you must ensure each of the servers has a different application name.
endif::params_multideploy[]
ifdef::params_mandatory_maven[]
** *Maven repository URL* (`MAVEN_REPO_URL`): A URL for a Maven repository. You must upload all the processes (KJAR files) that are to be deployed on managed {KIE_SERVERS} in your environment into this repository.
** *Maven repository username* (`MAVEN_REPO_USERNAME`): The username for the Maven repository.
** *Maven repository password* (`MAVEN_REPO_PASSWORD`): The username for the Maven repository.
endif::params_mandatory_maven[]
ifdef::params_kieserver_s2i[]
** *KIE Server Container Deployment* (`KIE_SERVER_CONTAINER_DEPLOYMENT`): The identifying information of the decision service (KJAR file) that is built from your source. The format is: `<containerId>=<groupId>:<artifactId>:<version>`. You can provide two or more KJAR files using the `|` separator, for example: `containerId=groupId:artifactId:version|c2=g2:a2:v2`. The Maven build process must produce all these files from the source in the Git repository.
** *Git Repository URL* (`SOURCE_REPOSITORY_URL`): The URL for the Git repository that contains the source for your decision service.
** *Git Reference* (`SOURCE_REPOSITORY_REF`): The branch in the Git repository
** *Context Directory* (`CONTEXT_DIR`): The path to the source within the project downloaded from the Git repository
** *Artifact Directory* (`ARTIFACT_DIR`): The path within the project that contains the required binary files (KJAR files and any other necessary files) after a successful Maven build. Normally this directory is the target directory of the build. However, you can provide prebuilt binaries in this directory in the Git repository
endif::params_kieserver_s2i[]
** *ImageStream Namespace* (`IMAGE_STREAM_NAMESPACE`): The namespace where the image streams are available. If the image streams were already available in your OpenShift environment (see <<imagestreams-file-install-proc>>), the namespace is `openshift`. If you have installed the image streams file, the namespace is the name of the OpenShift project.
ifdef::params_central[]
ifeval::["{LOCAL_CENTRAL}"=="{CENTRAL} Monitoring"]
** *{LOCAL_CENTRAL} Container Replicas* (`{CENTRAL_CAPITAL_UNDER}_MONITORING_CONTAINER_REPLICAS`): The number of replicas initially created for {CENTRAL} Monitoring. If you do not want to use a high-availability configuration for {CENTRAL} Monitoring, set this number to 1.
endif::[]
endif::params_central[]
** *KIE Server Container Replicas* (`KIE_SERVER_CONTAINER_REPLICAS`): The number of replicas initially created the {KIE_SERVER} instance.
ifdef::params_kieserver_container_deployment[]
+
. If you want to load and start services from the Maven repo at the startup of the {KIE_SERVER}, set the following parameter:
** *KIE Server Container Deployment* (`KIE_SERVER_CONTAINER_DEPLOYMENT`): The identifying information of the decision services (KJAR files) that the deployment must pull from the Maven repository. The format is: `<containerId>=<groupId>:<artifactId>:<version>`. You can provide two or more KJAR files using the `|` separator, for example: `containerId=groupId:artifactId:version|c2=g2:a2:v2`.
endif::params_kieserver_container_deployment[]
+
. If necessary, set the following user names and passwords. By default, the deployment automatically generates the passwords.
** *KIE Admin User* (`KIE_ADMIN_USER`) and *KIE Admin Password* (`KIE_ADMIN_PWD`): The user name and password for the administrative user in {CENTRAL} Monitoring.
ifdef::params_kieserver[]
** *KIE Server User* (`KIE_SERVER_USER`) and *KIE Server Password* (`KIE_SERVER_PWD`): The user name and password that a client application must use to connect to any of the {KIE_SERVERS}.
endif::params_kieserver[]
ifeval::["{subcontext}"=="freeform-monitor"]
+
. Ensure the following parameter remains at its default value:
** *KIE Server Startup Strategy* (`KIE_SERVER_STARTUP_STRATEGY`). This parameter must be set to `OpenShiftStartupStrategy` to ensure that {CENTRAL} Monitoring connects to all {KIE_SERVER} instances automatically, using an OpenShift API. The default value is `OpenShiftStartupStrategy`. Do not change this value.
endif::[]