[id='rn-known-issues-con']
= Known issues

This section lists known issues with {PRODUCT} {PRODUCT_VERSION}.

ifdef::PAM[]

== Installation

== {CENTRAL}

.In the DMN designer, when importing a data object from a Java class, a field of the Java Date type is not converted to the DMN date type [https://issues.redhat.com/browse/RHDM-1145[RHDM-1145]]

Issue: When you use DMN designer to import a data object from a Java class and the class has a field of type Date, the resulting DMN field is not of a DMN date type.

Steps to reproduce:

. Open a project in {CENTRAL}.
. Add a Java data object.
. Create a `java.util.Date` field in this object.
. Save and close the Java class.
. Open a DMN file.
. Select the *Data Types* tab.
. Click *Import Data Object*.
. Select the Java class that you created.
. Click *Import*.
. Check the type of the field into which the `java.util.Date` field was converted.

Expected result: The field has the type `date` or `date and time`.

Actual result: The field does ont have any of these two types.

Workaround: Manually change the type of the field to `date` or `date and time`.

//approved by Barbora Siskova
.You cannot start a task if the Elytron adapter is installed [https://issues.jboss.org/browse/RHPAM-2450[RHPAM-2450]]

Issue: If {CENTRAL} on {EAP} is integrated with RH-SSO using the Elytron adapter, errors are displayed after a task is started.

Steps to reproduce:

. Install {PRODUCT} on {EAP}.
. Configure {CENTRAL} with RH-SSO using the Elytron adapter.
. Import a process sample.
. Start the process.
. Start a task.

Expected result: The task starts correctly.

Actual result: The task does not start and an error is displayed.

Workaround: Use the legacy adapter instead of the Elytron adapter. Enter the following command to install the legacy adapter:

[source]
----
./bin/jboss-cli.sh -c --file=bin/adapter-install.cli
----


ifdef::PAM[]

//approved
.In the guided rule editor, you cannot use the `is contained in comma separated list` constraint in combination with complex values [https://issues.jboss.org/browse/RHPAM-2457[RHPAM-2457]]

Issue: In the guided rule editor, you cannot use the `is contained in comma separated list` constraint in combination with complex values. Complex values are values that contain a comma or are wrapped by brackets.

Workaround: None.

endif::[]

== High availability

//approved
.In a high-availability authoring environment, when one user imports a project, another user is unable to see it [https://issues.jboss.org/browse/RHPAM-2470[RHPAM-2470]]

Issue: When multiple users connect to a high-availability {CENTRAL} and one user creates a project, another user cannot see the project.

Steps to reproduce:

//approved
. Log in to {CENTRAL} as two different users (A and B) from two different hosts or browsers.
. As user A and as user B, open the same space.
. As user A, import a project using an external Git repository URL.

Expected result: As user B, you can see the imported project in the space.

Actual result: As user B, you cannot see the imported project in the space.

Workaround: As user B, reload the space.


//approved
.In a high-availability authoring environment, project creation fails when a {CENTRAL} node is down [https://issues.jboss.org/browse/RHPAM-2475[RHPAM-2475]]

Issue: When you create a project, the project creation does not complete. The cause is one {CENTRAL} node in a high-availability authoring environment going down.

Workaround: Create the project again.

//approved
.In a high-availability authoring environment, asset creation is not completed when a {CENTRAL} node is down [https://issues.jboss.org/browse/RHPAM-2476[RHPAM-2476]]

Issue: When you create an asset, the asset is not indexed. It is displayed in {CENTRAL} but you cannot use it. The cause is one {CENTRAL} node in a high-availability authoring environment going down.

Workaround: In the *Project Explorer* view, open the asset and click *Save*.

ifdef::PAM[]

== Process designer

//approved
.If you try to migrate a process with a sequence flow without the source and target nodes set, you should receive a warning message, but you do not [https://issues.jboss.org/browse/RHPAM-2453[RHPAM-2453]]

Issue: If a process in the legacy process designer contains a sequence flow without the source and target nodes set, and you try to migrate that process to the new process designer, you should receive a warning message, but you do not. It is also not possible to migrate process.

Steps to reproduce:

. Create a process in the legacy process designer.
. Add a sequence flow to the process, do not set the source and target nodes, and then save the process.
. Click the *Migrate* button.

Expected result: You see a message telling you that the source and target nodes for a sequence flow are not set and you cannot migrate the process.

Actual result: No message appears and you cannot migrate the process.

Workaround: None.

//approved
.If you migrate a process from the legacy process designer to the new process designer, you receive an incorrect warning that a node will be ignored [https://issues.jboss.org/browse/RHPAM-2452[RHPAM-2452]]

Issue:  If you migrate a process from the legacy process designer to the new process designer, you receive a warning that a node will be ignored. However, the node is not ignored and is migrated successfully.

Steps to reproduce:

. Create a Start to End process in the legacy process designer.
. Migrate the process to the new process designer.

Expected result: No warning about ignoring elements are shown if no elements will be ignored after migration.

Actual result: Warnings are shown that some unknown element will be ignored.

Workaround: Ignore the warnings and confirm that all nodes migrate successfully.

//approved
.In the new process designer, the warning message for migrating a `Group` element is missing [https://issues.jboss.org/browse/RHPAM-2454[RHPAM-2454]]

Issue: If you migrate a process that contains a `Group` element from the legacy process designer to the new process designer, the warning message about ignoring the node is missing.

Steps to reproduce:

. Create a process in the legacy process designer.
. Add a `Group` element to the process and then save the process.
. Migrate the process from the legacy process designer to the new process designer.

Expected result: You see a warning message about ignoring the node.

Actual result: You do not see the warning message.

Workaround: None.


endif::[]

== {OPENSHIFT}

.Product environment fails to deploy on Amazon Web Services (AWS) with AWS Elastic Block Storage (EBS) because of AWS EBS volume plugin lack of support for `ReadWriteMany` (`RWX`) persistent volume access mode [https://issues.jboss.org/browse/RHPAM-2480[RHPAM-2480]]

Issue: Several templates used for installing {PRODUCT} on {OPENSHIFT}, as well as deployment of several environment types using the Business Automation Operator, fail to deploy on AWS with EBS. The templates and environment types include persistent volume claims that require support for the `ReadWriteMany` access mode and the AWS EBS volume plugin does not provision persistent volumes with this access mode.

ifdef::PAM[]
The following templates are affected:

* `rhpam76-managed.yaml`
* `rhpam76-prod.yaml`
* `rhpam76-prod-immutable-monitor.yaml`
* `rhpam76-authoring.yaml`
* `rhpam76-authoring-ha.yaml`

endif::[]


ifdef::DM[]
The `rhdm76-authoring-ha.yaml` template is affected.

endif::[]

Workaround: Deploy an NFS server and provision the persistent volumes using NFS. For information about provisioning persistent volumes using NFS, see one of the following guides:

* For {OPENSHIFT} version 3, see the "Persistent storage using NFS" section of the  https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html/configuring_clusters/[OpenShift Container Platform 3.11 Installation and Configuration] guide.

* For {OPENSHIFT} version 4, see the "Persistent storage using NFS" section of the  https://access.redhat.com/documentation/en-us/openshift_container_platform/4.2/html/storage[OpenShift Container Platform 4.2 Storage] guide.

.OptaWeb Vehicle Routing tests fail due to different versions of dependencies [https://issues.jboss.org/browse/RHDM-1129[RHDM-1129]]

Issue: OptaWeb Vehicle Routing is distributed with the incorrect `package-lock.json` file. As a result, snapshot tests of the `optaweb-vehicle-routing-frontend` module fail because of changes in HTML code generated by different versions of dependencies.

Workaround:

. Change directory to the `optaweb-vehicle-routing-frontend` module.
. Enter the following command to download the required dependencies:
+
[source]
----
$ npm install
----
. Enter the following command to run the tests:
+
[source]
----
$ npm test
----
. Press the u key to update failing snapshots.

//approved
.The {KIE_SERVER} pod fails to start after a user updates the BusyBox image on {OPENSHIFT} [https://issues.jboss.org/browse/RHPAM-2431[RHPAM-2431]]

Issue: In a {OPENSHIFT} environment, a {KIE_SERVER} pod fails to start or restart with the latest version of the BusyBox image.

Steps to reproduce:

. In your {OPENSHIFT} environment, use a template or operator to deploy a {KIE_SERVER} that uses a MySQL or PostgreSQL database server.
. Enter the following command to manually update the OpenShift registry to the latest BusyBox image:
+
[source]
----
$ docker pull busybox
----

. Scale the {KIE_SERVER} pod down to 0 replicas and then scale up.

Expected result: The {KIE_SERVER} pod starts normally.

Actual result: The {KIE_SERVER} pod fails to start and remains at 0 replicas.

Workaround:

. On a local machine that has access to the cluster and has Docker installed, enter the following command to pull the BusyBox image version 1.28.4:
+
[source]
----
$ docker pull docker.io/busybox:1.28.4
----

. Enter the following command to tag the image with the latest tag:
+
[source]
----
docker tag docker.io/busybox:1.28.4 myopenshiftcluster/openshift/busybox:latest
----

. Push the image into your {OPENSHIFT} environment. For instructions, refer to the following documentation:
+
** For  {OPENSHIFT} version 3.11, see the "Accessing the Registry" section of the https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html-single/developer_guide/index[OpenShift Container Platform 3.11 Developer Guide].
** For  {OPENSHIFT} version 4.1, see the "Accessing the Registry" section of https://access.redhat.com/documentation/en-us/openshift_container_platform/4.1/html-single/registry/index[Configuring registries for OpenShift Container Platform 4.1].
