[id='message-send-event-proc_{context}']
= Creating an event that sends {KAFKA} messages

When designing your business process in {CENTRAL}, you can create an event that sends {KAFKA} messages. 

The event can have a data object as an input data item. The {PROCESS_ENGINE} sends the content of a data object as a message in the configured topic.

.Procedure

. Open the project that contains your business process in {CENTRAL}.
. Create a data object defining the data that the message must contain. For instructions about creating data objects, see {URL_DEVELOPING_PROCESS_SERVICES}#assembly-designing-business-processes[_{DESIGNING_BUSINESS_PROCESSES}_].
. Create a named message or event. Set the name of the message or event to the name of the {KAFKA} topic to which the messages must be sent. *??? HOW ??? Note: this is the biggest missing link right now* 
. Select the business process and open the business process designer.
. Add an intermediate throw event or an end event of the type _message_ or _signal_.
. Open the properties of the event.
. In the *Message* or *Signal* field, select the named message or signal that you created.
. Add an input data item. Select the data object that you created as its type.
. Save the business process.