[id='maven-external-configure-proc_{context}']

ifeval::["{context}" == "packaging-deploying"]
= Configuring an external Maven repository for {CENTRAL} and {KIE_SERVER}
endif::[]
ifeval::["{context}" == "install-on-eap"]
= Modify the Maven settings file
endif::[]
You can configure {CENTRAL} and {KIE_SERVER} to use an external Maven repository, such as Nexus or Artifactory, instead of the built-in repository. In this case, when you build projects in {CENTRAL}, all built project KJAR files are pushed into this external repository. You can progress these files through the repository as necessary to implement your integration process, and deploy the KJAR files using {CENTRAL} or the {KIE_SERVER} REST API.

.Prerequisites
* {CENTRAL} and {KIE_SERVER} are installed. For installation options, see {URL_PLANNING_INSTALL}[_{PLANNING_INSTALL}_].

[NOTE]
====
If you deploy your authoring environment on {OPENSHIFT}, you do not need to complete this procedure. Instead, set the `MAVEN_REPO_URL` parameter during deployment. For more information, see the following documents:
+
ifdef::PAM[]
{URL_DEPLOYING_AUTHORING_ON_OPENSHIFT}#template-deploy-optionalmaven-authoring-proc[_{DEPLOYING_AUTHORING_ON_OPENSHIFT}_]
endif::PAM[]
ifdef::DM[]
{URL_DEPLOYING_AUTHORING_MANAGED_ON_OPENSHIFT}#template-deploy-optionalmaven-authoring-proc[_{DEPLOYING_AUTHORING_MANAGED_ON_OPENSHIFT}_]
endif::DM[]
{URL_DEPLOYING_OPENSHIFT_OPERATOR}#operator-deploy-kieserver-proc[_{DEPLOYING_OPENSHIFT_OPERATOR}_]
====


.Procedure
. Create a Maven `settings.xml` file with connection and access details for your external repository. For details about the `settings.xml` file, see the Maven link:https://maven.apache.org/settings.html[Settings Reference].
. Save the file in a known location, for example, `/opt/custom-config/settings.xml`.
. In your {PRODUCT} installation directory, navigate to the `standalone-full.xml` file. For example, if you use a {EAP} installation for {PRODUCT}, go to `$EAP_HOME/standalone/configuration/standalone-full.xml`.
. Open `standalone-full.xml` and under the `<system-properties>` tag, set the `kie.maven.settings.custom` property to the full path name of the `settings.xml` file.
+
For example:
+
[source,xml]
----
<property name="kie.maven.settings.custom" value="/opt/custom-config/settings.xml"/>
----
+
. Start or restart {CENTRAL} and {KIE_SERVER}.

.Next steps

You must also edit the `pom.xml` file for every project, so that Maven pushes the KJAR artifacts for the project into the external Maven repository. For instructions, see <<export-project-to-maven>>.
