[id='er-shiftroster-proc']
= Viewing and editing shifts in the shift roster

The Shift Roster is a table of all spots and all possible time spans. 

If an employee must be present in a spot during a time spans, a _shift_ must exist for this spot and this time spans. If a spot requires several employees at the same time, you can create several shifts for the same spot and time spans.

Each shift is represented by a rectangle at the intersection of a spot (row) and time span (column).

When new time is added to the draft period, the application copies the shifts (and default employees, if present) from the rotation pattern into this new part of the draft period. You can also add and edit shifts in the draft period manually. 

.Procedure
. To view and edit the shift roster, click the *Shift Roster* tab.
. In the top right part of the browser window, the *Week of* field lists the week for which the roster is displayed, To view other weeks, use the *<* and *>* buttons.
. To add a shift, click an open area of the schedule. The application adds a shift, determining the slot and time span automatically from the location of the click.
. To edit a shift, click the shift. You can set the following values for a shift:
** *From* and *To* date and time: The exact time and duration of the shift.
** *Employee*: The employee assigned to the shift by default.
** *Pinned*: Whether the employee is _pinned_ to the shift. If an employee is pinned, automatic employee rostering can not change the assignment of the employee to the shift. a pinned employee is not automatically replicated to any other shift.
+
To save the changes, click *Apply*.
. To delete a shift, click the shift, then click *Delete shift*.
